// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CYRetailIMS.Domain.Common;
using Microsoft.EntityFrameworkCore;

namespace CYRetailIMS.Domain.Entities;

[PrimaryKey("BranchCode", "ReceiptDate")]
[Table("TMReceiptNumber")]
public partial class TMReceiptNumber : BaseEntity
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string BranchCode { get; set; }

    [Key]
    public DateOnly ReceiptDate { get; set; }

    public int RunningNo { get; set; }
}