// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using CYRetailIMS.Domain.Common;
using Microsoft.EntityFrameworkCore;

namespace CYRetailIMS.Domain.Entities;

[Table("TTReceipt")]
[Index("ReceiptNo", Name = "UQ__TTReceip__CC0B72A619AACF41", IsUnique = true)]
public partial class TTReceipt : BaseEntity
{
    [Key]
    public int ReceiptID { get; set; }

    public int TransactionID { get; set; }

    [Required]
    [StringLength(50)]
    public string ReceiptNo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string CreatedBy { get; set; }

    [ForeignKey("TransactionID")]
    [InverseProperty("TTReceipts")]
    public virtual TTTransaction Transaction { get; set; }
}