<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CYRetailIMS.Application</RootNamespace>
    <AssemblyName>CYRetailIMS.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Caching\" />
    <Folder Include="Services\EmployeeService\Commands\DeleteEmployee\" />
    <Folder Include="Services\EmployeeService\Commands\UpdateEmployee\" />
    <Folder Include="Services\EmployeeService\EventHandlers\" />
    <Folder Include="Services\EmployeeService\Queries\" />
    <Folder Include="Services\DepartmentService\" />
    <Folder Include="Services\MenuService\Commands\" />
    <Folder Include="Services\MenuService\EventHandlers\" />
    <Folder Include="Services\MenuService\Queries\GetMenuByRoleID\" />
    <Folder Include="Services\MenuService\Queries\GetMenuList\" />
    <Folder Include="Services\RoleService\" />
    <Folder Include="Services\UserService\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.6.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
