<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>CYRetailIMS.Application</RootNamespace>
    <AssemblyName>CYRetailIMS.Application</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Caching\" />
    <Folder Include="Common\Mappings\UI\Sale\" />
    <Folder Include="Services\ItemService\Queries\GetItemByBarcode\v2\" />
    <Folder Include="Services\MoneyTransferService\Commands\" />
    <Folder Include="Services\MoneyTransferService\EventHandlers\" />
    <Folder Include="Services\SupplierContactTypeService\Commands\" />
    <Folder Include="Services\SupplierContactTypeService\EventHandlers\" />
    <Folder Include="Services\PaymentTypeService\Commands\" />
    <Folder Include="Services\PaymentTypeService\EventHandlers\" />
    <Folder Include="Services\PurchaseTypeService\Commands\" />
    <Folder Include="Services\PurchaseTypeService\EventHandlers\" />
    <Folder Include="Services\AccountService\Commands\" />
    <Folder Include="Services\AccountService\EventHandlers\" />
    <Folder Include="Services\AdjustItemTransactionService\Commands\DeleteAdjustItem\" />
    <Folder Include="Services\AdjustItemTypeService\Commands\" />
    <Folder Include="Services\AdjustItemTypeService\EventHandlers\" />
    <Folder Include="Services\ApproveStatusService\Commands\" />
    <Folder Include="Services\ApproveStatusService\EventHandlers\" />
    <Folder Include="Services\CurrencyService\Commands\" />
    <Folder Include="Services\CurrencyService\EventHandlers\" />
    <Folder Include="Services\DepartmentService\Commands\" />
    <Folder Include="Services\DepartmentService\EventHandlers\" />
    <Folder Include="Services\ItemBrandService\Commands\UpdateBrand\v1\" />
    <Folder Include="Services\ItemInBranchService\Commands\CreateItemInBranch\v1\" />
    <Folder Include="Services\ItemTransferStatusService\Commands\" />
    <Folder Include="Services\ItemTransferStatusService\EventHandlers\" />
    <Folder Include="Services\ItemTypeService\EventHandlers\" />
    <Folder Include="Services\ItemTypeService\Commands\" />
    <Folder Include="Services\MenuService\Commands\" />
    <Folder Include="Services\MenuService\EventHandlers\" />
    <Folder Include="Services\MenuService\Queries\GetMenuList\v1\" />
    <Folder Include="Services\ReportService\Commands\DeleteAuditReport\" />
    <Folder Include="Services\ReportService\Commands\UpdateAuditReport\" />
    <Folder Include="Services\ReportService\EventHandlers\" />
    <Folder Include="Services\RoleInMenuService\Queries\" />
    <Folder Include="Services\RoleService\Commands\" />
    <Folder Include="Services\RoleService\EventHandlers\" />
    <Folder Include="Services\ShipmentTypeService\Commands\" />
    <Folder Include="Services\ShipmentTypeService\EventHandlers\" />
    <Folder Include="Services\SupplierTypeService\Commands\" />
    <Folder Include="Services\SupplierTypeService\EventHandlers\" />
    <Folder Include="Services\TransactionService\Queries\GetTransactionByTransactionTypeID\" />
    <Folder Include="Services\TransactionService\Queries\GetTransactionByTransactionDate\" />
    <Folder Include="Services\TransactionService\Queries\GetTransactionByCreatedBy\" />
    <Folder Include="Services\TransactionService\Queries\GetTransactionByItemID\" />
    <Folder Include="Services\TransactionService\Queries\GetTransactionByBranchCode\" />
    <Folder Include="Services\TransferTypeService\Commands\" />
    <Folder Include="Services\TransferTypeService\EventHandlers\" />
    <Folder Include="Services\UnitOfMeasureService\Commands\" />
    <Folder Include="Services\UnitOfMeasureService\EventHandlers\" />
    <Folder Include="Services\UserInBranchService\Commands\" />
    <Folder Include="Services\UserInBranchService\EventHandlers\" />
    <Folder Include="Services\WarehouseService\Commands\" />
    <Folder Include="Services\WarehouseService\EventHandlers\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="EPPlus.Core" Version="1.5.4" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.6.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.5.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.4.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
